# Setup
title:        transparent Software-Defined Exchange (tSDX)
tagline:      SDN for Optical Networks
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       TOAN
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
